; Lower FPS compared to default due to view distance increase

; If motion blur is turning back on even with in-game settings off add the command below
; r.MotionBlur.Max=0

[SystemSettings]
r.ParallelFrustumCull=1
r.StaticMeshLODDistanceScale=0.5
r.ScreenSizeCullRatioFactor=1
r.SceneColorFringeQuality=0
; Remove r.Tonemapper.Quality=1 if you use bloom and find some scenes bright
r.Tonemapper.Quality=1
r.AODownsampleFactor=1
r.AmbientOcclusion.Intensity=-1
r.AmbientOcclusionMaxQuality=100
r.Shadow.RadiusThreshold=0.01
r.Shadow.MaxCSMResolution=4096
r.Shadow.PerObjectResolutionMax=2048
r.Shadow.PerObjectResolutionMin=2048
r.DetailMode=2
r.MaterialQualityLevel=3
r.KuroMaterialQualityLevel=3
r.ViewDistanceScale=2.0
foliage.LODDistanceScale=3.0
foliage.DensityScaleLOD.DrawCallOptimize=1
r.SSR.MaxRoughness=1.0
r.SSR.HalfResSceneColor=0
r.Kuro.KuroTyndallScatteringsDownSampleFactor=1
r.KuroVolumetricLight.ColorMaskDownSampleFactor=1
r.KuroVolumetricLight.DownSampleFactor=1
r.LightShaftDownSampleFactor=1
r.Upscale.Quality=3
a.URO.ForceAnimRate=1
r.VRS.EnableMaterial=false
r.VRS.EnableMesh=false
r.PSO.LRUCapacity=3072
r.Streaming.MinBoost=1.5
r.Streaming.PoolSize=2304
r.Streaming.PoolSizeForMeshes=1024
r.Streaming.UsingKuroStreamingPriority=0
r.Kuro.Foliage.GrassCullDistanceMax=23350
r.Kuro.Foliage.Grass3_0CullDistanceMax=26700
wp.Runtime.SoraGridBlackListHeight=20000
wp.Runtime.PlannedLoadingRangeScale=1.0