; Lower FPS compared to default due to view distance increase

; If motion blur is turning back on even with in-game settings off add the command below
; r.MotionBlur.Max=0

[SystemSettings]
r.ParallelFrustumCull=1
r.ParallelOcclusionCull=1
r.StaticMeshLODDistanceScale=0.5
r.ScreenSizeCullRatioFactor=3
r.Kuro.KuroEnableFFTBloom=1
r.Kuro.KuroEnableToonFFTBloom=1
r.Kuro.KuroBloomStreak=1
r.EnableLensflareSceneSample=1
r.DepthOfFieldQuality=2
r.SceneColorFringeQuality=0
; Remove r.Tonemapper.Quality=1 if you use bloom and find some scenes bright
r.Tonemapper.Quality=1
r.AODownsampleFactor=2
r.AmbientOcclusion.Intensity=-1
r.AmbientOcclusionMaxQuality=100
r.Shadow.RadiusThreshold=0.01
r.Shadow.PerObjectResolutionMax=1024
r.Shadow.PerObjectResolutionMin=1024
r.DetailMode=2
r.MaterialQualityLevel=1
r.KuroMaterialQualityLevel=1
r.ViewDistanceScale=2.0
foliage.LODDistanceScale=2.0
foliage.DensityScaleLOD.DrawCallOptimize=1
r.SSR.MaxRoughness=1.0
r.SSR.HalfResSceneColor=0
r.Kuro.KuroTyndallScatteringsDownSampleFactor=1
r.KuroVolumetricLight.ColorMaskDownSampleFactor=1
r.KuroVolumetricLight.DownSampleFactor=1
r.LightShaftDownSampleFactor=1
r.Upscale.Quality=3
a.URO.ForceAnimRate=1
r.VRS.EnableMaterial=false
r.VRS.EnableMesh=false
; If textures still load late or blurry, increase r.Streaming.MinBoost and r.Streaming.PoolSize values but uses more VRAM
r.Streaming.MinBoost=2.0
; Can increase r.Streaming.PoolSize to 2560 if using GPU with 16GB VRAM
r.Streaming.PoolSize=1536
r.streaming.MeshMaxKeepMips=15
r.streaming.TextureMaxKeepMips=15
r.Streaming.UsingKuroStreamingPriority=0
r.Kuro.Foliage.GrassCullDistanceMax=17500
r.Kuro.Foliage.Grass3_0CullDistanceMax=20000
wp.Runtime.SoraGridBlackListHeight=15000
wp.Runtime.PlannedLoadingRangeScale=1.0
Kuro.Script.EnableCSharpEnv=true

; RT is disabled, set r.RayTracing.LoadConfig to 1 if you use it before launching game
[/Script/Engine.RendererSettings]
r.MaxAnisotropy=16
r.RayTracing.LoadConfig=0