; If motion blur is turning back on even with in-game settings off add the command below
; r.MotionBlur.Max=0

; For GPUs with 6GB VRAM or higher (1080p) - To fix blurry textures for certain stuff you can add the command below
; r.Streaming.MinBoost=2.0
; r.Streaming.PoolSize=1024

[SystemSettings]
r.StaticMeshLODDistanceScale=0.7
r.ScreenSizeCullRatioFactor=3
r.Kuro.KuroEnableFFTBloom=1
r.Kuro.KuroEnableToonFFTBloom=1
r.Kuro.KuroBloomStreak=1
r.EnableLensflareSceneSample=1
r.DepthOfFieldQuality=2
r.SceneColorFringeQuality=0
; Remove r.Tonemapper.Quality=1 if you use bloom and find some scenes bright
r.Tonemapper.Quality=1
r.AODownsampleFactor=2
r.AmbientOcclusion.Intensity=-1
r.AmbientOcclusionMaxQuality=100
r.Shadow.RadiusThreshold=0.03
r.Shadow.MaxCSMResolution=512
r.Shadow.MaxResolution=512
r.Shadow.MinResolution=512
r.Shadow.PerObjectShadowMapResolution=512
r.Shadow.PerObjectResolutionMax=512
r.Shadow.PerObjectResolutionMin=512
r.DetailMode=1
r.MaterialQualityLevel=2
r.KuroMaterialQualityLevel=2
foliage.DensityScaleLOD.DrawCallOptimize=1
r.SSR.MaxRoughness=1.0
r.SSR.HalfResSceneColor=0
r.Kuro.KuroTyndallScatteringsDownSampleFactor=2
r.KuroVolumetricLight.ColorMaskDownSampleFactor=2
r.KuroVolumetricLight.DownSampleFactor=2
r.LightShaftDownSampleFactor=1
r.Upscale.Quality=3
a.URO.ForceAnimRate=1
r.VRS.EnableMaterial=false
r.VRS.EnableMesh=false
r.streaming.MeshMaxKeepMips=15
r.streaming.TextureMaxKeepMips=15
r.Streaming.UsingKuroStreamingPriority=0
wp.Runtime.SoraGridBlackListHeight=7500
wp.Runtime.PlannedLoadingRangeScale=0.6
Kuro.Script.EnableCSharpEnv=true

[/Script/Engine.RendererSettings]
r.MaxAnisotropy=16
r.RayTracing.LoadConfig=0