; If motion blur is turning back on even with in-game settings off add the command below
; r.MotionBlur.Max=0

[SystemSettings]
; Reduce r.SecondaryScreenPercentage.GameViewport to 83 or lower if you need more FPS
r.SecondaryScreenPercentage.GameViewport=100
r.Kuro.MaterialDesktopQualityShoulderRender=0
r.StaticMeshLODDistanceScale=0.7
r.ScreenSizeCullRatioFactor=10
r.Kuro.KuroEnableFFTBloom=0
r.Kuro.KuroEnableToonFFTBloom=0
r.Kuro.KuroBloomStreak=1
r.EnableLensflareSceneSample=1
r.DepthOfFieldQuality=2
r.SceneColorFringeQuality=0
; Remove r.Tonemapper.Quality=1 if you use bloom and find some scenes bright
r.Tonemapper.Quality=1
r.AmbientOcclusionMaxQuality=0
r.Shadow.DistanceScale=0.6
r.Shadow.RadiusThreshold=0.06
r.Shadow.MaxCSMResolution=256
r.Shadow.MaxResolution=256
r.Shadow.MinResolution=256
r.Shadow.PerObjectShadowMapResolution=256
r.Shadow.PerObjectResolutionMax=256
r.Shadow.PerObjectResolutionMin=256
r.Shadow.ForbidHISMShadowStartIndex=0
r.DetailMode=0
r.MaterialQualityLevel=2
r.KuroMaterialQualityLevel=2
; If you want grass back remove foliage.CullAll=1
foliage.CullAll=1
foliage.DensityScaleLOD.DrawCallOptimize=1
r.ViewDistanceScale=0.8
r.SSR.Quality=0
r.Upscale.Quality=3
r.Kuro.InteractionEffect.EnableBushInteractionEffect=0
r.Kuro.InteractionEffect.EnableFoliageEffect=0
r.Kuro.InteractionEffect.UseCppWaterEffect=0
r.KuroVolumeCloudEnable=0
a.URO.ForceAnimRate=1
r.SSFS=0
r.VRS.EnableMaterial=false
r.VRS.EnableMesh=false
r.streaming.MeshMaxKeepMips=15
r.streaming.TextureMaxKeepMips=15
wp.Runtime.PlannedLoadingRangeScale=0.4

[/Script/Engine.RendererSettings]
r.MaxAnisotropy=4
r.RayTracing.LoadConfig=0