; If motion blur is turning back on even with in-game settings off add the command below
; r.MotionBlur.Max=0

[SystemSettings]
; Reduce r.SecondaryScreenPercentage.GameViewport to 83 or lower if you need more FPS
r.SecondaryScreenPercentage.GameViewport=100
r.ParallelFrustumCull=1
r.ScreenSizeCullRatioFactor=10
; --- Post Processing ---
;r.DepthOfFieldQuality=0
;r.Tonemapper.Quality=1
r.SceneColorFringeQuality=0
; --- Shadows ---
r.Shadow.DistanceScale=0.6
r.Shadow.RadiusThreshold=0.06
r.Shadow.MaxCSMResolution=256
r.Shadow.MaxResolution=256
r.Shadow.PerObjectShadowMapResolution=256
r.Shadow.PerObjectResolutionMax=256
r.Shadow.PerObjectResolutionMin=256
; --- Ambient Occlusion ---
r.AmbientOcclusionMaxQuality=0
; --- View Distance / LoD / Material Quality ---
r.StaticMeshLODDistanceScale=0.7
r.DetailMode=0
r.MaterialQualityLevel=2
r.KuroMaterialQualityLevel=2
r.ViewDistanceScale=0.8
wp.Runtime.PlannedLoadingRangeScale=0.4
r.Kuro.MaterialDesktopQualityShoulderRender=0
; --- Streaming / Texture ---
; If using GPU with 4GB VRAM
; Can increase r.Streaming.PoolSize & r.Streaming.PoolSizeForMeshes to 768
r.Streaming.PoolSize=512
r.Streaming.PoolSizeForMeshes=512
r.Streaming.UsingKuroStreamingPriority=0
; --- Reflections / Others ---
r.SSR.Quality=0
r.PSO.LRUCapacity=1536
a.URO.ForceAnimRate=1
r.Upscale.Quality=3
foliage.DensityScaleLOD.DrawCallOptimize=1
r.Kuro.InteractionEffect.EnableBushInteractionEffect=0
r.Kuro.InteractionEffect.EnableFoliageEffect=0
r.Kuro.InteractionEffect.UseCppWaterEffect=0
r.KuroVolumeCloudEnable=0
r.SSFS=0
; If you want grass back remove foliage.CullAll=1
foliage.CullAll=1
r.VRS.EnableMaterial=false
r.VRS.EnableMesh=false